
NAME := Debug.a
FANCY_NAME := Engine/Debug

################################################################

DIR_SRC := src/
DIR_OBJ := obj/

################################################################

FILES += \
	Debug.cpp \

################################################################

LIBRARYS  := $(NAME)
INCLUDES  := include/ ../ValueType/include/ ../Generics/include/ ../FileManager/include
ARGUMENTS := 

################################################################

BASE_DIR := ../

include $(BASE_DIR)/MakefileArchiver.mk

################################################################
