
NAME := PolyHedra.a
FANCY_NAME := Engine/PolyHedra

################################################################

DIR_SRC := src/PolyHedra/
DIR_OBJ := obj/PolyHedra/

################################################################

FILES := \

################################################################

FILES += \
	Data.cpp \
	PolyHedra.cpp \
	FileCollection.cpp \
	Parser.cpp \
	Generate.cpp \
\
	Skin/Data.cpp \
	Skin/Skin.cpp \
	Skin/Parsing.cpp \

################################################################

LIBRARYS  := $(NAME)
INCLUDES  := include/ ../Debug/include ../ValueType/include ../Generics/include ../FileManager/include ../OpenGL/include ../Graphics/include
ARGUMENTS := 

# Graphics only used to generate Textures
# put in Skin / somewhere else

################################################################

BASE_DIR := ../

include $(BASE_DIR)/MakefileArchiver.mk

################################################################
