
NAME := PolyGon.a
FANCY_NAME := Engine/PolyGon

################################################################

DIR_SRC := src/
DIR_OBJ := obj/

################################################################

FILES := \

################################################################

FILES += \
	PolyGon.cpp \
\
	Graphics/Full/Main/Data.cpp \
	Graphics/Full/Main/Layout.cpp \
	Graphics/Full/ShaderLayout.cpp \
\
	Graphics/Wire/Main/Layout.cpp \
	Graphics/Wire/ShaderLayout.cpp \
\
	InstanceManager.cpp \
	ObjectData.cpp \
	Manager.cpp \
	Object.cpp \

################################################################

LIBRARYS  := $(NAME)
INCLUDES  := include/ ../ValueType/include ../Generics/include ../FileManager/include ../OpenGL/include ../Display/include ../Graphics/include ../User/include
ARGUMENTS := 

################################################################

BASE_DIR := ../

include $(BASE_DIR)/MakefileArchiver.mk

################################################################
