#include "UserParameter/KeyBoard/Codes.hpp"
#include "OpenGL.hpp"



// Space
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::Space(GLFW_KEY_SPACE);

// Numbers
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::D0(GLFW_KEY_0);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::D1(GLFW_KEY_1);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::D2(GLFW_KEY_2);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::D3(GLFW_KEY_3);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::D4(GLFW_KEY_4);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::D5(GLFW_KEY_5);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::D6(GLFW_KEY_6);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::D7(GLFW_KEY_7);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::D8(GLFW_KEY_8);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::D9(GLFW_KEY_9);

// Letters
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::A(GLFW_KEY_A);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::B(GLFW_KEY_B);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::C(GLFW_KEY_C);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::D(GLFW_KEY_D);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::E(GLFW_KEY_E);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::F(GLFW_KEY_F);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::G(GLFW_KEY_G);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::H(GLFW_KEY_H);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::I(GLFW_KEY_I);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::J(GLFW_KEY_J);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::K(GLFW_KEY_K);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::L(GLFW_KEY_L);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::M(GLFW_KEY_M);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::N(GLFW_KEY_N);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::O(GLFW_KEY_O);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::P(GLFW_KEY_P);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::Q(GLFW_KEY_Q);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::R(GLFW_KEY_R);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::S(GLFW_KEY_S);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::T(GLFW_KEY_T);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::U(GLFW_KEY_U);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::V(GLFW_KEY_V);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::W(GLFW_KEY_W);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::X(GLFW_KEY_X);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::Y(GLFW_KEY_Y);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::Z(GLFW_KEY_Z);

// Control0
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::Escape(GLFW_KEY_ESCAPE);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::Enter(GLFW_KEY_ENTER);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::Tab(GLFW_KEY_TAB);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::Backspace(GLFW_KEY_BACKSPACE);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::Insert(GLFW_KEY_INSERT);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::Delete(GLFW_KEY_DELETE);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::Right(GLFW_KEY_RIGHT);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::Left(GLFW_KEY_LEFT);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::Down(GLFW_KEY_DOWN);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::Up(GLFW_KEY_UP);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::PageUp(GLFW_KEY_PAGE_UP);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::PageDown(GLFW_KEY_PAGE_DOWN);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::Home(GLFW_KEY_HOME);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::End(GLFW_KEY_END);

// Function
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::F1(GLFW_KEY_F1);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::F2(GLFW_KEY_F2);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::F3(GLFW_KEY_F3);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::F4(GLFW_KEY_F4);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::F5(GLFW_KEY_F5);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::F6(GLFW_KEY_F6);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::F7(GLFW_KEY_F7);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::F8(GLFW_KEY_F8);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::F9(GLFW_KEY_F9);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::F10(GLFW_KEY_F10);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::F11(GLFW_KEY_F11);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::F12(GLFW_KEY_F12);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::F13(GLFW_KEY_F13);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::F14(GLFW_KEY_F14);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::F15(GLFW_KEY_F15);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::F16(GLFW_KEY_F16);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::F17(GLFW_KEY_F17);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::F18(GLFW_KEY_F18);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::F19(GLFW_KEY_F19);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::F20(GLFW_KEY_F20);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::F21(GLFW_KEY_F21);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::F22(GLFW_KEY_F22);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::F23(GLFW_KEY_F23);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::F24(GLFW_KEY_F24);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::F25(GLFW_KEY_F25);

// KeyPad
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::KeyPad0(GLFW_KEY_KP_0);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::KeyPad1(GLFW_KEY_KP_1);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::KeyPad2(GLFW_KEY_KP_2);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::KeyPad3(GLFW_KEY_KP_3);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::KeyPad4(GLFW_KEY_KP_4);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::KeyPad5(GLFW_KEY_KP_5);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::KeyPad6(GLFW_KEY_KP_6);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::KeyPad7(GLFW_KEY_KP_7);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::KeyPad8(GLFW_KEY_KP_8);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::KeyPad9(GLFW_KEY_KP_9);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::KeyPadDecimal(GLFW_KEY_KP_DECIMAL);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::KeyPadDiv(GLFW_KEY_KP_DIVIDE);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::KeyPadMul(GLFW_KEY_KP_MULTIPLY);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::KeyPadSub(GLFW_KEY_KP_SUBTRACT);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::KeyPadAdd(GLFW_KEY_KP_ADD);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::KeyPadEnter(GLFW_KEY_KP_ENTER);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::KeyPadEqual(GLFW_KEY_KP_EQUAL);

// Control1
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::LeftShift(GLFW_KEY_LEFT_SHIFT);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::LeftControl(GLFW_KEY_LEFT_CONTROL);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::LeftAlt(GLFW_KEY_LEFT_ALT);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::LeftSuper(GLFW_KEY_LEFT_SUPER);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::RightShift(GLFW_KEY_RIGHT_SHIFT);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::RightControl(GLFW_KEY_RIGHT_CONTROL);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::RightAlt(GLFW_KEY_RIGHT_ALT);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::RightSuper(GLFW_KEY_RIGHT_SUPER);
UserParameter::Haptic::Code UserParameter::KeyBoard::Keys::Menu(GLFW_KEY_MENU);
